# this is a generated file, to avoid over-writing it just delete this comment
require 'jar_dependencies'

require_jar( 'com.fasterxml.jackson.core', 'jackson-core', '2.5.3' )
require_jar( 'com.amazonaws', 'aws-java-sdk-kms', '1.10.27' )
require_jar( 'org.apache.httpcomponents', 'httpcore', '4.3.3' )
require_jar( 'log4j', 'log4j', '1.2.17' )
require_jar( 'com.amazonaws', 'aws-java-sdk-cloudwatch', '1.10.20' )
require_jar( 'com.amazonaws', 'aws-java-sdk-core', '1.10.27' )
require_jar( 'com.beust', 'jcommander', '1.48' )
require_jar( 'com.amazonaws', 'dynamodb-import-export-tool', '1.0.0' )
require_jar( 'commons-lang', 'commons-lang', '2.6' )
require_jar( 'joda-time', 'joda-time', '2.8.1' )
require_jar( 'commons-logging', 'commons-logging', '1.1.3' )
require_jar( 'com.amazonaws', 'dynamodb-streams-kinesis-adapter', '1.0.2' )
require_jar( 'com.amazonaws', 'aws-java-sdk-kinesis', '1.10.20' )
require_jar( 'com.amazonaws', 'aws-java-sdk-s3', '1.10.27' )
require_jar( 'org.apache.httpcomponents', 'httpclient', '4.3.6' )
require_jar( 'com.amazonaws', 'aws-java-sdk-dynamodb', '1.10.27' )
require_jar( 'com.fasterxml.jackson.core', 'jackson-databind', '2.5.3' )
require_jar( 'com.amazonaws', 'amazon-kinesis-client', '1.6.1' )
require_jar( 'commons-codec', 'commons-codec', '1.6' )
require_jar( 'com.fasterxml.jackson.core', 'jackson-annotations', '2.5.0' )
require_jar( 'com.google.protobuf', 'protobuf-java', '2.6.1' )
require_jar( 'com.google.guava', 'guava', '15.0' )
